# Generated by Django 4.2.6 on 2023-11-26 20:04

import bank_services.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankServices',
            fields=[
                ('bank_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, null=True)),
                ('order_img', models.CharField(blank=True, null=True)),
                ('service_status', models.CharField(default='действует', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('surname', models.CharField(blank=True, null=True)),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('admin_flag', models.BooleanField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', bank_services.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_status', models.CharField(default='черновик', max_length=20)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_admin_set', to='bank_services.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank_services.users')),
            ],
        ),
        migrations.CreateModel(
            name='RequestsServices',
            fields=[
                ('bill', models.CharField(blank=True, max_length=100, null=True)),
                ('rs_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank_services.bankservices')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank_services.requests')),
            ],
            options={
                'unique_together': {('bank_service_id', 'request_id')},
            },
        ),
    ]
