# Generated by Django 4.2.4 on 2023-10-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestsservices',
            old_name='bank_service',
            new_name='bank_service_id',
        ),
        migrations.RenameField(
            model_name='requestsservices',
            old_name='request',
            new_name='request_id',
        ),
        migrations.AlterUniqueTogether(
            name='requestsservices',
            unique_together={('bank_service_id', 'request_id')},
        ),
    ]
