# Generated by Django 4.2.4 on 2023-10-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0002_rename_bank_service_requestsservices_bank_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='formation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
