# Generated by Django 4.2.6 on 2023-12-20 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0002_alter_requests_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='rating',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 20, 20, 23, 20, 942721, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
