# Generated by Django 4.2.4 on 2023-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0003_alter_requests_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='formation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
