# Generated by Django 4.2.6 on 2023-12-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0003_requests_rating_alter_requests_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankservices',
            name='price',
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 26, 12, 34, 34, 864813, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
