# Generated by Django 4.2.6 on 2023-12-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0004_remove_bankservices_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankservices',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 26, 15, 58, 45, 232328, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
