# Generated by Django 4.2.6 on 2023-10-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0005_alter_requests_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankservices',
            name='img',
            field=models.CharField(blank=True, default='jpg', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankservices',
            name='order_img',
            field=models.CharField(blank=True, default='jpg', max_length=10, null=True),
        ),
    ]
