# Generated by Django 4.2.6 on 2023-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0006_alter_bankservices_img_alter_bankservices_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.CharField(blank=True, null=True),
        ),
    ]
