# Generated by Django 4.2.6 on 2023-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0007_users_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankservices',
            name='img',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankservices',
            name='order_img',
            field=models.CharField(blank=True, null=True),
        ),
    ]
