# Generated by Django 4.2.6 on 2023-12-26 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_services', '0008_alter_requests_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 26, 16, 8, 54, 856030, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
